app:
  name: "trading_bot"
  timezone: "Asia/Tokyo"

paths:
  preprocess_dir: "./preprocess"
  data_dir: "./data"
  features_dir: "./features"
  models_dir: "./models"
  backtest_dir: "./backtest"
  trade_dir: "./trade"
  logs_dir: "./logs"